builds:
  - binary: new
    goos:
      - windows
      - darwin
      - linux

archive:
  format_overrides:
    - goos: windows
      format: zip

  files:
    - install.sh

brew:
  # Name template of the recipe
  # Default to project name
  name: myproject

  # Repository to push the tap to.
  github:
    owner: divanvisagie
    name: homebrew-tap
  
  homepage: "https://github.com/divanvisagie/new"

