builds:
  - binary: new
    goos:
      - windows
      - darwin
      - linux

archive:
  format_overrides:
    - goos: windows
      format: zip

  files:
    - install.sh

brew:
  name: new

  # Repository to push the tap to.
  github:
    owner: divanvisagie
    name: homebrew-tap
  
  homepage: "https://github.com/divanvisagie/new"

scoop:
  bucket:
    owner: divanvisagie
    name: scoop-bucket

  homepage: "https://github.com/divanvisagie/new"