language: go

go:
  - 1.11.2

script: 
  - go test ./...
  - go build main.go
  - rm main
 
after_success:
  - go get "golang.org/x/sys/windows"
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash